services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: segmentation_api
    # Mappe le port 8000 du conteneur au port 8000 de votre machine hôte
    ports:
      - "8000:8000"
    environment:
      # Variables d'environnement pour configurer les URLs du modèle.
      # Facile à changer ici sans reconstruire l'image.
      - MODEL_URL=https://github.com/emmanuelouedraogo/voiture-autonaume/releases/download/v0.0.2/final_optimized_model.keras
      - CONFIG_URL=https://github.com/emmanuelouedraogo/voiture-autonaume/releases/download/v0.0.2/class_mapping.json
      - CLASS_WEIGHTS_URL=https://github.com/emmanuelouedraogo/voiture-autonaume/releases/download/v0.0.2/class_weights.json
    healthcheck:
      # Commande pour vérifier la santé. curl -f échoue si le code HTTP est une erreur (>=400)
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s # Vérifier toutes les 30 secondes
      timeout: 10s # Attendre 10 secondes pour une réponse
      retries: 3 # 3 tentatives échouées avant de marquer comme "unhealthy"
      # Période de grâce au démarrage pour que le modèle ait le temps de se télécharger et de se charger
      start_period: 120s