services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: segmentation_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_PATH=models/final_optimized_model.keras
      - CONFIG_PATH=models/class_mapping.json
      - CLASS_WEIGHTS_PATH=models/class_weights.json
      # URLs pour télécharger les modèles si les fichiers ci-dessus ne sont pas trouvés
      - MODEL_URL=https://github.com/emmanuelouedraogo/voiture-autonaume/releases/download/v0.1.0/final_optimized_model.keras
      - CONFIG_URL=https://github.com/emmanuelouedraogo/voiture-autonaume/releases/download/v0.1.0/class_mapping.json
      - CLASS_WEIGHTS_URL=https://github.com/emmanuelouedraogo/voiture-autonaume/releases/download/v0.1.0/class_weights.json
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 120s