# Nom du workflow
name: Run Python Tests

# Déclencheurs : s'exécute à chaque push sur la branche main ou sur les pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Définition des jobs
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Tester sur plusieurs versions de Python pour assurer la compatibilité
        python-version: ["3.12"]

    steps:
    # Étape 1: Récupérer le code source de votre dépôt
    - name: Checkout repository
      uses: actions/checkout@v4

    # Étape 2: Configurer l'environnement Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Étape 3: Installer les dépendances (y compris les dépendances de test comme pytest)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]

    # Étape 4: Exécuter les tests avec pytest
    - name: Run tests with pytest
      run: >-
        pytest --cov=emmanuel_segmentation_package --cov-report=xml

    # Étape 5 (Optionnel): Uploader le rapport de couverture
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Nécessite de configurer un secret dans GitHub
        files: ./coverage.xml
        fail_ci_if_error: true